"""fixed tx hash issue 2

Revision ID: 260abf6fecd9
Revises: e9693e85ca72
Create Date: 2025-10-28 18:43:53.748910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260abf6fecd9'
down_revision: Union[str, Sequence[str], None] = 'e9693e85ca72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('token_transfers_tx_hash_fkey'), 'token_transfers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('token_transfers_tx_hash_fkey'), 'token_transfers', 'transactions', ['tx_hash'], ['tx_hash'])
    # ### end Alembic commands ###
