"""add id and pk to token_transfers

Revision ID: 34f1e0c3833d
Revises: 4d2608eda1c1
Create Date: 2025-10-28 04:20:49.437237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f1e0c3833d'
down_revision: Union[str, Sequence[str], None] = '4d2608eda1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # drop current primary key that includes tx_hash so we can make tx_hash nullable
    op.drop_constraint('token_transfers_pkey', 'token_transfers', type_='primary')

    # now alter tx_hash nullable
    op.alter_column('token_transfers', 'tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # add id column (nullable first), create sequence and populate values, then set NOT NULL
    op.add_column('token_transfers', sa.Column('id', sa.Integer(), nullable=True))
    op.execute("CREATE SEQUENCE IF NOT EXISTS token_transfers_id_seq OWNED BY token_transfers.id;")
    op.execute("UPDATE token_transfers SET id = nextval('token_transfers_id_seq') WHERE id IS NULL;")
    op.alter_column('token_transfers', 'id', existing_type=sa.Integer(), nullable=False)

    # create new primary key on id
    op.create_primary_key('token_transfers_pkey', 'token_transfers', ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_transfers_pkey', 'token_transfers', type_='primary')
    op.alter_column('token_transfers', 'tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('token_transfers', 'id')
    # ### end Alembic commands ###
