"""add wallet_id to token_transfers

Revision ID: e7d01c6ba0e3
Revises: 
Create Date: 2025-10-28 04:04:38.315837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d01c6ba0e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_transfers', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.add_column('token_transfers', sa.Column('chain', sa.String(), nullable=True))
    op.add_column('token_transfers', sa.Column('token_decimal', sa.Integer(), nullable=True))
    op.add_column('token_transfers', sa.Column('token_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'token_transfers', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_transfers', type_='foreignkey')
    op.drop_column('token_transfers', 'token_name')
    op.drop_column('token_transfers', 'token_decimal')
    op.drop_column('token_transfers', 'chain')
    op.drop_column('token_transfers', 'wallet_id')
    # ### end Alembic commands ###
